### ISSUE TITLE
Password Incorrect

### ISSUE THREAD

**Issue by Iawkeys** [saiakarsh193/chessmen-online#1]
When I try to start the server it say password incorrect and I can't reset the password too because I need password to do it can you give the initial password ?

**Comment by saiakarsh193** [comment]
Hey @KylianBasset! So I made this intentionally. The first time setting up the password is done manually (to avoid chicken and egg problem!). You can do the following.

check the `server_password` hash in the [env_yaml](https://github.com/saiakarsh193/chessmen-online/blob/master/env.yaml#L4) file. Replace this hash with the new password hash. You can generate the new hash using this code:

```python
import hashlib

passwd = "hello world"
passwd_hash = hashlib.md5(passwd.encode()).hexdigest()
print(passwd_hash)
````

Once the new password hash has been written manually, you are all set. Next time you can just use this password to do server-side stuff. By the way, this implementation has obvious security issues. I was just playing around with admin security, and will later fix it. Let me know if you have any other issues or suggestions regarding the code in general. The current implementation only allows CLI-based gameplay over LAN. The code will soon get a GUI update as well. Look out for that. Cheers!
